#include <benchmark/benchmark.h>
#include <libraw/libraw.h>

#define BENCHMARK_FILE(MAKER, CAMERA, FORMAT)                                  \
    static void CAMERA##_##FORMAT(benchmark::State &state)                     \
    {                                                                          \
        for (auto _ : state)                                                   \
        {                                                                      \
            RawProcessor.open_file("samples/" #MAKER "/" #CAMERA "." #FORMAT); \
            RawProcessor.unpack();                                             \
            RawProcessor.dcraw_process();                                      \
        }                                                                      \
    }                                                                          \
    BENCHMARK(CAMERA##_##FORMAT)->MinTime(10.0);

LibRaw RawProcessor;

// Benchmark each RAW file
BENCHMARK_FILE(canon, canon_eos_1d_mark_iii_hevc, cr3)
BENCHMARK_FILE(canon, canon_eos_1d_mark_iii_jpeg, cr3)
BENCHMARK_FILE(canon, canon_eos_1dx_mark_ii, cr2)
BENCHMARK_FILE(canon, canon_eos_2000d, cr2)
BENCHMARK_FILE(canon, canon_eos_20d, cr2)
BENCHMARK_FILE(canon, canon_eos_400d, cr2)
BENCHMARK_FILE(canon, canon_eos_5d_mark_iii, cr2)
BENCHMARK_FILE(canon, canon_eos_600d, cr2)
BENCHMARK_FILE(canon, canon_eos_digital_rebel_xsi, cr2)
BENCHMARK_FILE(canon, canon_eos_m10, cr2)
BENCHMARK_FILE(canon, canon_eos_rp, cr3)
BENCHMARK_FILE(canon, canon_powershot_a550, crw)
BENCHMARK_FILE(canon, canon_powershot_a610, raw)
BENCHMARK_FILE(canon, canon_powershot_a650, crw)
BENCHMARK_FILE(canon, canon_powershot_elph_180, crw)
BENCHMARK_FILE(canon, canon_powershot_g12, cr2)
BENCHMARK_FILE(canon, canon_powershot_g15, cr2)
BENCHMARK_FILE(canon, canon_powershot_g6, crw)
BENCHMARK_FILE(canon, canon_powershot_g7, crw)
BENCHMARK_FILE(canon, canon_powershot_pro1, crw)
BENCHMARK_FILE(canon, canon_powershot_pro70, crw)
BENCHMARK_FILE(canon, canon_powershot_pro90_is, crw)
BENCHMARK_FILE(canon, canon_powershot_s110, cr2)
BENCHMARK_FILE(canon, canon_powershot_s1x, cr2)
BENCHMARK_FILE(canon, canon_powershot_s30, crw)
BENCHMARK_FILE(canon, canon_powershot_s3_is, crw)
BENCHMARK_FILE(canon, canon_powershot_s45, crw)
BENCHMARK_FILE(canon, canon_powershot_s60, crw)
BENCHMARK_FILE(canon, canon_powershot_sd750, crw)
BENCHMARK_FILE(canon, canon_powershot_sx150_is, cr2)
BENCHMARK_FILE(canon, canon_powershot_sx260_hs, crw)
BENCHMARK_FILE(canon, canon_powershot_sx40_hs, cr2)
BENCHMARK_FILE(fuji, fuji_finepix_f710, raf)
BENCHMARK_FILE(fuji, fuji_finepix_hs30_exr, raf)
BENCHMARK_FILE(fuji, fuji_finepix_s5500, raf)
BENCHMARK_FILE(fuji, fuji_x10, raf)
BENCHMARK_FILE(fuji, fuji_x20, raf)
BENCHMARK_FILE(fuji, fuji_x_a5, raf)
BENCHMARK_FILE(fuji, fuji_x_e2, raf)
BENCHMARK_FILE(fuji, fuji_x_t10, raf)
BENCHMARK_FILE(kodak, kodak_dcs560c, dcr)
BENCHMARK_FILE(kodak, kodak_dcs620x, dcr)
BENCHMARK_FILE(kodak, kodak_dcs760c, dcr)
BENCHMARK_FILE(kodak, kodak_p850, kdc)
BENCHMARK_FILE(leaf, leaf_valeo_7, mos)
BENCHMARK_FILE(leica, leica_d_lux2, raw)
BENCHMARK_FILE(leica, leica_d_lux3, raw)
BENCHMARK_FILE(leica, leica_digilux_3, raw)
BENCHMARK_FILE(minolta, minolta_dimage_7hi, mrw)
BENCHMARK_FILE(minolta, minolta_dimage_a2, mrw)
BENCHMARK_FILE(nikon, nikon_d1h, nef)
BENCHMARK_FILE(nikon, nikon_d2hs, nef)
BENCHMARK_FILE(nikon, nikon_d300s, nef)
BENCHMARK_FILE(nikon, nikon_d4s, nef)
BENCHMARK_FILE(nikon, nikon_d5000, nef)
BENCHMARK_FILE(nikon, nikon_d5300, nef)
BENCHMARK_FILE(nikon, nikon_d5600, nef)
BENCHMARK_FILE(nikon, nikon_d7500, nef)
BENCHMARK_FILE(nikon, nikon_d810, nef)
BENCHMARK_FILE(nikon, nikon_d90, nef)
BENCHMARK_FILE(nikon, nikon_e2100, raw)
BENCHMARK_FILE(nikon, nikon_e3700, raw)
BENCHMARK_FILE(nikon, nikon_e4300, raw)
BENCHMARK_FILE(nikon, nikon_e5000, raw)
BENCHMARK_FILE(nikon, nikon_e5700, nef)
BENCHMARK_FILE(nikon, nikon_e900, raw)
BENCHMARK_FILE(nikon, nikon_j1, nef)
BENCHMARK_FILE(nikon, nikon_p330, nrw)
BENCHMARK_FILE(nikon, nikon_z7, nef)
BENCHMARK_FILE(olympus, olympus_c5050z, orf)
BENCHMARK_FILE(olympus, olympus_c5060wz, orf)
BENCHMARK_FILE(olympus, olympus_e_30, orf)
BENCHMARK_FILE(olympus, olympus_e_5, orf)
BENCHMARK_FILE(olympus, olympus_e_620, orf)
BENCHMARK_FILE(olympus, olympus_sh_2, orf)
BENCHMARK_FILE(olympus, olympus_sp500uz, orf)
BENCHMARK_FILE(olympus, olympus_stylus_1, orf)
BENCHMARK_FILE(others, Sony_A99_gps_acr, dng)
BENCHMARK_FILE(others, isg_2020x1520, raw)
BENCHMARK_FILE(others, lg_g4_iso_800, dng)
BENCHMARK_FILE(others, logitch_fotoman_pixtura, raw)
BENCHMARK_FILE(others, pixelink_a782, raw)
BENCHMARK_FILE(others, rollei_d530flex, rdc)
BENCHMARK_FILE(others, sigma_sd14, x3f)
BENCHMARK_FILE(panasonic, panasonic_dmc_fz150, rw2)
BENCHMARK_FILE(panasonic, panasonic_dmc_fz200, rw2)
BENCHMARK_FILE(panasonic, panasonic_dmc_fz330, rw2)
BENCHMARK_FILE(panasonic, panasonic_dmc_fz38, rw2)
BENCHMARK_FILE(panasonic, panasonic_dmc_gf1, rw2)
BENCHMARK_FILE(panasonic, panasonic_dmc_gh2, rw2)
BENCHMARK_FILE(panasonic, panasonic_dmc_gh5, rw2)
BENCHMARK_FILE(panasonic, panasonic_dmc_lx10, rw2)
BENCHMARK_FILE(panasonic, panasonic_dmc_lx7, rw2)
BENCHMARK_FILE(pentax, pentax_k100d_super, pef)
BENCHMARK_FILE(pentax, pentax_k20d, dng)
BENCHMARK_FILE(phase_one, phase_one_h_20, raw)
BENCHMARK_FILE(samsung, samsung_nx3000, srw)
BENCHMARK_FILE(sony, sony_alpha_nex5n, arw)
BENCHMARK_FILE(sony, sony_dsc_r1, sr2)
BENCHMARK_FILE(sony, sony_dsc_hx99, arw)
BENCHMARK_FILE(sony, sony_dsc_rx100, arw)
BENCHMARK_FILE(sony, sony_dsc_rx100_iv, arw)
BENCHMARK_FILE(sony, sony_dsc_rx10_ii, arw)
BENCHMARK_FILE(sony, sony_dsc_rx10_iii, arw)
BENCHMARK_FILE(sony, sony_dsc_rx10_iv, arw)
BENCHMARK_FILE(sony, sony_dsc_rx1r_ii, arw)
BENCHMARK_FILE(sony, sony_dslr_a100, arw)
BENCHMARK_FILE(sony, sony_dslr_a3000, arw)
BENCHMARK_FILE(sony, sony_dslr_a350, arw)
BENCHMARK_FILE(sony, sony_dslr_a380, arw)
BENCHMARK_FILE(sony, sony_dslr_a450, arw)
BENCHMARK_FILE(sony, sony_dslr_a500, arw)
BENCHMARK_FILE(sony, sony_dslr_a6000, arw)
BENCHMARK_FILE(sony, sony_dslr_a6400, arw)
BENCHMARK_FILE(sony, sony_dslr_a68, arw)
BENCHMARK_FILE(sony, sony_dslr_a700, arw)
BENCHMARK_FILE(sony, sony_dslr_a7r_iii, arw)
BENCHMARK_FILE(sony, sony_dslr_a9, arw)
BENCHMARK_FILE(sony, sony_slt_a55, arw)
BENCHMARK_FILE(sony, sony_slt_a57, arw)
BENCHMARK_FILE(sony, sony_slt_a77v, arw)
BENCHMARK_FILE(sony, sony_slt_a99v, arw)

BENCHMARK_MAIN();